### PR TITLE
Fix/async tests

### LINKED ISSUE #102: Rejection of async functions not tested correctly
The actual implementation of the unit tests for the async functions of the client is flawed.

Here's a example: [test/test_getAgent.js#L40](https://github.com/craft-ai/craft-ai-client-js/blob/master/test/test_getAgent.js#L40).

In the above test, there is no guarantee that the call to `client.deleteAgent(agentId)` fails. The async call could as well resolve and pass the test which is not expected at all.

[Mocha](https://mochajs.org) suggests to use the plugin [chai-as-promised](https://www.npmjs.com/package/chai-as-promised) in their [documentation](https://mochajs.org/#working-with-promises).

### PR DESCRIPTION
**Pull request by cloderic**
fixes #102

### CODE REVIEW

File: test/test_getSharedAgentInspectorUrl.js [hunk 1]
```diff
@@ -70,9 +70,12 @@ describe('client.sharedAgentInspectorUrl(<agentId>, <timestamp>)', function() {
       .then(res => {
         expect(res).to.be.null;
       })
-      .catch((err) => {
-        expect(err.name).to.be.equal('CraftAiTimeError');
-        expect(err.message).to.be.equal('Time error, given "toto" is invalid.');
-      });
+      .then(
```
Comment (alexisfontaine) [inline test/test_getSharedAgentInspectorUrl.js]: The previous resolve and its assertion are not needed anymore.

File: test/test_addAgentContextOperations.js [hunk 2]
```diff
@@ -220,19 +204,13 @@ describe('client.addAgentContextOperations(<agentId>, <operations>)', function()
...
-      })
-      .then(() => {
-        return client.getAgentContextOperations(agents[0].id);
-      })
-      .then(retrievedOperations => {
-        expect(retrievedOperations).to.be.deep.equal(CONFIGURATION_1_OPERATIONS_1);
-      });
+      .then(
+        () => Promise.reject(new Error('Should not be reached')),
+        err => {
```
Comment (alexisfontaine) [inline test/test_addAgentContextOperations.js]: You could have written:
```js
  .then(() => Promise.reject(new Error('Should not be reached')))
  .catch(err => { ... })
```
which is a bit easier to read.
